import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import type { inferProcedureOutput } from "@trpc/server";
import type { AppRouter } from "@acme/api";
import { useAuth, UserButton } from "@clerk/nextjs";
import Link from "next/link";
import { useFireEvent, useIdentifyUser } from "@lvl-up/react";
import { UserAwardsSection } from "../components/user-awards";
import { AwardsSection } from "../components/awards-section";
import { RedeemsSection } from "../components/redeems-section";
import { useEffect } from "react";
import Streak from "../components/streak";

const PostCard: React.FC<{
  post: inferProcedureOutput<AppRouter["post"]["all"]>[number];
}> = ({ post }) => {
  return (
    <div className="max-w-2xl rounded-lg border-2 border-gray-500 p-4 transition-all hover:scale-[101%]">
      <h2 className="text-2xl font-bold text-[hsl(280,100%,70%)]">
        {post.title}
      </h2>
      <p>{post.content}</p>
    </div>
  );
};

const Home: NextPage = () => {
  const postQuery = trpc.post.all.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> Turbo
          </h1>
          <AuthShowcase />

          <div className="flex h-[60vh] justify-center overflow-y-scroll px-4 text-2xl">
            {postQuery.data ? (
              <div className="flex flex-col gap-4">
                {postQuery.data?.map((p) => {
                  return <PostCard key={p.id} post={p} />;
                })}
              </div>
            ) : (
              <p>Loading..</p>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const [user, identify] = useIdentifyUser();
  const { mutate: fireEvent } = useFireEvent();
  const { isSignedIn, userId } = useAuth();
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined,
    { enabled: !!isSignedIn },
  );

  useEffect(() => {
    if (!isSignedIn) return;
    identify(userId);
  }, [isSignedIn, userId, identify]);

  const handleClick = () => {
    if (!userId) return;
    fireEvent({
      userId,
      eventKey: "user_says_hi",
    });
  };

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      {isSignedIn && (
        <>
          <p className="text-center text-2xl text-white">
            {secretMessage && (
              <span>
                {" "}
                {secretMessage} click the user button!
                <br />
              </span>
            )}
          </p>
          <div className="flex items-center justify-center">
            <div className="flex w-full flex-col justify-end rounded-lg bg-white p-4">
              <div className="flex flex-row-reverse items-center gap-2">
                <UserButton
                  appearance={{
                    elements: {
                      userButtonAvatarBox: {
                        width: "3rem",
                        height: "3rem",
                      },
                    },
                  }}
                />
                <div className="text-center text-lg font-bold text-black">
                  {user?.points} points
                </div>
              </div>
              <Streak streak={user?.streak} />
            </div>
          </div>
          <div className="mt-2 flex items-center justify-center">
            <button className="rounded-sm p-4" onClick={handleClick}>
              Fire Event!
            </button>
          </div>
          <UserAwardsSection />
        </>
      )}
      {!isSignedIn && (
        <p className="text-center text-2xl text-white">
          <Link href="/sign-in">Sign In</Link>
        </p>
      )}
      <AwardsSection />
      <RedeemsSection />
    </div>
  );
};
